#!/bin/bash

set -ex

# We download some files that we do not maintain in this software package.
# The meson build system does not provide a method to download individual
# files as a pre-configure step.  Meson has a git sub-module which they
# call wrap dependency; but we don't need a whole git repository as a
# sub-module (that would lead to source redundancy and file bloat), just a
# few files.  Hence we provide this wget download script to be run before
# all meson build scripts.  If we find a bug in any of this downloaded
# source, we'll work on it (or make our own fork of the source files).
# Having a build script that downloads files from the web is a very bad
# idea that is problematic for operating system software distributions; so
# this is a separate script that must be run before the meson build
# scripts.  Tarballs when created will include these downloaded files.

# related meson github issue:
# https://github.com/mesonbuild/meson/issues/16162

# I very much doubt that I can influence the development of meson.  A
# major defect I see is that meson does not separate the "setup: step from
# the wrap-file downloading, so the way I see it meson makes making an
# operating system from source much more difficult than it needs to be.
# The downloading of source files should be the first and separate step in
# the build process; it's obvious when you note that you cannot build
# software without all the source files.  Cool operating systems, like
# Gentoo, that build and install from source files have to work around
# this meson defect.  The basic rule is that any file download step
# should happen before any configuration/setup step.  That would be
# a big design change to meson.


# This "art" project tends to have two name prefix's libart and art.  We
# picked the shorter name of the two, art, for our bash variable name
# prefix.  They have a good white paper on it (see following Homepage
# link).  We did a benchmark of this with other packages at
# https://github.com/lanceman2/dictionary_benchmark/
#
# Homepage:
# https://github.com/armon/libart/
#
# Thu Feb 11 10:01:08 2021:  301046804af165269e37da6725f5a4aec9ecc881
#
#art_tag=master
art_tag=301046804af165269e37da6725f5a4aec9ecc881
art_url=https://raw.githubusercontent.com/armon/libart/$art_tag/src/art
art_c_sha512sum=
art_h_sha512sum=



# Go to the directory there this script is.
cd $(dirname ${BASH_SOURCE[0]})

# This is the last file we get:
check_file=include/art.h

if [ -e ${check_file} ] ; then
    echo "File \"${check_file}\" is present"
    exit 0
fi

# A temporary directory to put downloaded source code files:
tmpDir=tmp_downloaded

if [ -d $tmpDir ] ; then
    # Here's hoping the developer did not put any developed source here:
    rm -rf $tmpDir
fi


# GetFile DIR FILENAME URL [SHA512SUM]
# $0      $1  $2       $3  $4
function GetFile() {

    [ -n "$3" ] || exit 1

    cd $1

    if [ ! -e "$2" ] ; then
        wget --no-check-certificate "$3" -O "$2"
    fi

    if [ -n "$4" ] ; then
        # We wanted a particular file, so we check its' sha512 sum.
        echo "$4  $2" | sha512sum -c
    else
        sha512sum "$2"
    fi

    cd -
}


mkdir $tmpDir


GetFile . ${tmpDir}/art.c $art_url.c $art_c_sha512sum
GetFile . ${tmpDir}/art.h $art_url.h $art_h_sha512sum

# If we made it to here, we very likely have all the files.
#

# Now move them to where we want them to stay.

mv ${tmpDir}/art.c lib/dict
mv ${tmpDir}/art.h include/


rmdir $tmpDir


set +x
echo -e "\n$0 Success"
